#!/usr/bin/env python3
import argparse

def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('example')
    return parser.parse_args()

def main():
    args = get_args()

if __name__ == '__main__':
    main()
